import { ResultRecipe, ResultRecipeDetail } from './recipe';

export const RECIPES: ResultRecipe = {
  results: [
    {
      id: 642977,
      title: 'Fish Pie With Fresh and Smoked Salmon',
      image: 'https://spoonacular.com/recipeImages/642977-312x231.jpg',
      imageType: 'jpg',
    },
    {
      id: 649730,
      title: 'Lemon Pie',
      image: 'https://spoonacular.com/recipeImages/649730-312x231.jpg',
      imageType: 'jpg',
    },
    {
      id: 655145,
      title: 'Peach Pie',
      image: 'https://spoonacular.com/recipeImages/655145-312x231.jpg',
      imageType: 'jpg',
    },
    {
      id: 632573,
      title: 'Apple Pie Bars',
      image: 'https://spoonacular.com/recipeImages/632573-312x231.jpg',
      imageType: 'jpg',
    },
    {
      id: 632575,
      title: 'Apple Pie Smoothie',
      image: 'https://spoonacular.com/recipeImages/632575-312x231.jpg',
      imageType: 'jpg',
    },
    {
      id: 632577,
      title: 'Apple Pie Pancakes',
      image: 'https://spoonacular.com/recipeImages/632577-312x231.jpg',
      imageType: 'jpg',
    },
    {
      id: 637797,
      title: 'Chess Pie Two Ways',
      image: 'https://spoonacular.com/recipeImages/637797-312x231.jpg',
      imageType: 'jpg',
    },
    {
      id: 655514,
      title: 'Pecan Pie Cheesecake',
      image: 'https://spoonacular.com/recipeImages/655514-312x231.jpg',
      imageType: 'jpg',
    },
    {
      id: 632570,
      title: 'Apple Pie Honey Wheat Scones',
      image: 'https://spoonacular.com/recipeImages/632570-312x231.jpg',
      imageType: 'jpg',
    },
    {
      id: 638568,
      title: 'Chili Pie with Green Chile and Cheddar Cornbread Crust',
      image: 'https://spoonacular.com/recipeImages/638568-312x231.jpg',
      imageType: 'jpg',
    },
    {
      id: 632167,
      title: 'Almond Pie',
      image: 'https://spoonacular.com/recipeImages/632167-312x231.jpg',
      imageType: 'jpg',
    },
    {
      id: 648883,
      title: 'Kidney Pie',
      image: 'https://spoonacular.com/recipeImages/648883-312x231.jpg',
      imageType: 'jpg',
    },
    {
      id: 650325,
      title: 'Loquat Pie',
      image: 'https://spoonacular.com/recipeImages/650325-312x231.jpg',
      imageType: 'jpg',
    },
    {
      id: 640182,
      title: 'Cottage Pie',
      image: 'https://spoonacular.com/recipeImages/640182-312x231.jpg',
      imageType: 'jpg',
    },
    {
      id: 662663,
      title: 'Sweetie Pie Soup',
      image: 'https://spoonacular.com/recipeImages/662663-312x231.jpg',
      imageType: 'jpg',
    },
    {
      id: 657359,
      title: 'Pumpkin Pie Smoothie',
      image: 'https://spoonacular.com/recipeImages/657359-312x231.jpg',
      imageType: 'jpg',
    },
  ],
  offset: 0,
  number: 16,
  totalResults: 136,
};

export const RECIPE: ResultRecipeDetail = {
  id: 655145,
  title: 'Peach Pie',
  readyInMinutes: 45,
  servings: 6,
  vegetarian: true,
  vegan: false,
  glutenFree: false,
  dairyFree: false,
  veryHealthy: false,
  cheap: false,
  veryPopular: false,
  sustainable: false,
  weightWatcherSmartPoints: 23,
  gaps: 'no',
  lowFodmap: false,
  aggregateLikes: 7,
  spoonacularScore: 32.0,
  healthScore: 3.0,
  creditsText: 'Foodista.com – The Cooking Encyclopedia Everyone Can Edit',
  license: 'CC BY 3.0',
  sourceName: 'Foodista',
  pricePerServing: 173.52,
  originalId: null,
  spoonacularSourceUrl: 'https://spoonacular.com/peach-pie-655145',
  sourceUrl: 'http://www.foodista.com/recipe/V45YG86D/peach-pie',
  image: 'https://spoonacular.com/recipeImages/655145-556x370.jpg',
  imageType: 'jpg',
  summary:
    'Peach Pie is a <b>vegetarian</b> dessert. This recipe makes 6 servings with <b>543 calories</b>, <b>9g of protein</b>, and <b>37g of fat</b> each. For <b>$1.69 per serving</b>, this recipe <b>covers 11%</b> of your daily requirements of vitamins and minerals. This recipe from Foodista has 7 fans. A mixture of cut up peaches, vanillan extract, brown eggs, and a handful of other ingredients are all it takes to make this recipe so flavorful. From preparation to the plate, this recipe takes about <b>45 minutes</b>. All things considered, we decided this recipe <b>deserves a spoonacular score of 33%</b>. This score is rather bad. Try <a href="https://spoonacular.com/recipes/old-fashioned-peach-pie-909789">Old-Fashioned Peach Pie</a>, <a href="https://spoonacular.com/recipes/cherry-pie-908329">Cherry Pie</a>, and <a href="https://spoonacular.com/recipes/butterfinger-pie-917550">Butterfinger Pie</a> for similar recipes.',
  cuisines: [],
  dishTypes: ['side dish'],
  diets: ['lacto ovo vegetarian'],
  occasions: [],
  winePairing: {},
  instructions:
    '<ol><li>Preheat the oven at 375. Place the pastry dough on a 9 inch round pie plate. Poke lightly the pastry and prebake for 8 minutes in the hot oven. Remove and set aside.</li><li>In a large bowl mix together the eggs, almond paste, heavy cream, brown sugar and vanilla extract.</li><li>Add the cut up peaches to the pastry shell, cover with the eggs mixture.</li><li>Bake at 350 for 45 minutes, or until the middle is solid firm.</li></ol>',
  extendedIngredients: [
    {
      id: 12071,
      aisle: 'Baking',
      image: 'marzipan-or-almond-paste.jpg',
      consistency: 'solid',
      name: 'almond paste',
      original: '3 ounces almond paste, crumbled',
      originalString: '3 ounces almond paste, crumbled',
      originalName: 'almond paste, crumbled',
      amount: 3.0,
      unit: 'ounces',
      meta: ['crumbled'],
      metaInformation: ['crumbled'],
      measures: {
        us: {
          amount: 3.0,
          unitShort: 'oz',
          unitLong: 'ounces',
        },
        metric: {
          amount: 85.049,
          unitShort: 'g',
          unitLong: 'grams',
        },
      },
    },
    {
      id: 19334,
      aisle: 'Baking',
      image: 'light-brown-sugar.jpg',
      consistency: 'solid',
      name: 'brown sugar',
      original: '1/2 cup - Brown Sugar',
      originalString: '1/2 cup - Brown Sugar',
      originalName: 'Brown Sugar',
      amount: 0.5,
      unit: 'cup',
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 0.5,
          unitShort: 'cups',
          unitLong: 'cups',
        },
        metric: {
          amount: 118.294,
          unitShort: 'ml',
          unitLong: 'milliliters',
        },
      },
    },
    {
      id: 1123,
      aisle: 'Milk, Eggs, Other Dairy',
      image: 'egg.png',
      consistency: 'solid',
      name: 'eggs',
      original: '4 large brown eggs',
      originalString: '4 large brown eggs',
      originalName: 'brown eggs',
      amount: 4.0,
      unit: 'large',
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 4.0,
          unitShort: 'large',
          unitLong: 'larges',
        },
        metric: {
          amount: 4.0,
          unitShort: 'large',
          unitLong: 'larges',
        },
      },
    },
    {
      id: 1053,
      aisle: 'Milk, Eggs, Other Dairy',
      image: 'fluid-cream.jpg',
      consistency: 'liquid',
      name: 'heavy cream',
      original: '2 cups heavy cream',
      originalString: '2 cups heavy cream',
      originalName: 'heavy cream',
      amount: 2.0,
      unit: 'cups',
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 2.0,
          unitShort: 'cups',
          unitLong: 'cups',
        },
        metric: {
          amount: 473.176,
          unitShort: 'ml',
          unitLong: 'milliliters',
        },
      },
    },
    {
      id: 10018338,
      aisle: 'Refrigerated;Frozen',
      image: 'dough.jpg',
      consistency: 'solid',
      name: 'pastry crust',
      original: 'Pastry crust',
      originalString: 'Pastry crust',
      originalName: 'Pastry crust',
      amount: 6.0,
      unit: 'servings',
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 6.0,
          unitShort: 'servings',
          unitLong: 'servings',
        },
        metric: {
          amount: 6.0,
          unitShort: 'servings',
          unitLong: 'servings',
        },
      },
    },
    {
      id: 9236,
      aisle: 'Produce',
      image: 'peach.png',
      consistency: 'solid',
      name: 'peaches',
      original: '3 cups cut up peaches, large chunks',
      originalString: '3 cups cut up peaches, large chunks',
      originalName: 'cut up peaches, large chunks',
      amount: 3.0,
      unit: 'cups',
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 3.0,
          unitShort: 'cups',
          unitLong: 'cups',
        },
        metric: {
          amount: 709.764,
          unitShort: 'ml',
          unitLong: 'milliliters',
        },
      },
    },
    {
      id: 2050,
      aisle: 'Baking',
      image: 'vanilla-extract.jpg',
      consistency: 'liquid',
      name: 'vanilla extract',
      original: '1 tablespoon vanilla extract',
      originalString: '1 tablespoon vanilla extract',
      originalName: 'vanilla extract',
      amount: 1.0,
      unit: 'tablespoon',
      meta: [],
      metaInformation: [],
      measures: {
        us: {
          amount: 1.0,
          unitShort: 'Tbsp',
          unitLong: 'Tbsp',
        },
        metric: {
          amount: 1.0,
          unitShort: 'Tbsp',
          unitLong: 'Tbsp',
        },
      },
    },
  ],
  analyzedInstructions: [
    {
      name: '',
      steps: [
        {
          number: 1,
          step: 'Preheat the oven at 37',
          ingredients: [],
          equipment: [
            {
              id: 404784,
              name: 'oven',
              localizedName: 'oven',
              image: 'oven.jpg',
            },
          ],
        },
        {
          number: 2,
          step:
            'Place the pastry dough on a 9 inch round pie plate. Poke lightly the pastry and prebake for 8 minutes in the hot oven.',
          ingredients: [
            {
              id: 10018338,
              name: 'pastry dough',
              localizedName: 'pastry dough',
              image: 'dough.jpg',
            },
          ],
          equipment: [
            {
              id: 404784,
              name: 'oven',
              localizedName: 'oven',
              image: 'oven.jpg',
            },
          ],
          length: {
            number: 8,
            unit: 'minutes',
          },
        },
        {
          number: 3,
          step:
            'Remove and set aside.In a large bowl mix together the eggs, almond paste, heavy cream, brown sugar and vanilla extract.',
          ingredients: [
            {
              id: 2050,
              name: 'vanilla extract',
              localizedName: 'vanilla extract',
              image: 'vanilla-extract.jpg',
            },
            {
              id: 12071,
              name: 'almond paste',
              localizedName: 'almond paste',
              image: 'marzipan-or-almond-paste.jpg',
            },
            {
              id: 19334,
              name: 'brown sugar',
              localizedName: 'brown sugar',
              image: 'dark-brown-sugar.png',
            },
            {
              id: 1053,
              name: 'heavy cream',
              localizedName: 'heavy cream',
              image: 'fluid-cream.jpg',
            },
            {
              id: 1123,
              name: 'egg',
              localizedName: 'egg',
              image: 'egg.png',
            },
          ],
          equipment: [
            {
              id: 404783,
              name: 'bowl',
              localizedName: 'bowl',
              image: 'bowl.jpg',
            },
          ],
        },
        {
          number: 4,
          step:
            'Add the cut up peaches to the pastry shell, cover with the eggs mixture.',
          ingredients: [
            {
              id: 0,
              name: 'pastry shells',
              localizedName: 'pastry shells',
              image: 'tartlet-shells.jpg',
            },
            {
              id: 9236,
              name: 'peach',
              localizedName: 'peach',
              image: 'peach.png',
            },
            {
              id: 1123,
              name: 'egg',
              localizedName: 'egg',
              image: 'egg.png',
            },
          ],
          equipment: [],
        },
        {
          number: 5,
          step:
            'Bake at 350 for 45 minutes, or until the middle is solid firm.',
          ingredients: [],
          equipment: [
            {
              id: 404784,
              name: 'oven',
              localizedName: 'oven',
              image: 'oven.jpg',
            },
          ],
          length: {
            number: 45,
            unit: 'minutes',
          },
        },
      ],
    },
  ],
};
